<?php

namespace backend\controllers\user;

use Yii;
use dektrium\user\controllers\RegistrationController as BaseRegistrationController;

class RegistrationController extends BaseRegistrationController
{

    public function actionRegister()
    {
       $this->layout = Yii::$app->user->isGuest ? '@backend/views/layouts/main-login.php' : 'main';
        return parent::actionRegister(); // TODO: Change the autogenerated stub
    }

    public function actionResend()
    {
        $this->layout = Yii::$app->user->isGuest ? '@backend/views/layouts/main-login.php' : 'main';
        return parent::actionResend(); // TODO: Change the autogenerated stub
    }
}