<?php

namespace backend\modules\inventoryInvoices\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii2tech\ar\softdelete\SoftDeleteBehavior;
use yii2tech\ar\softdelete\SoftDeleteQueryBehavior;

/**
 * This is the model class for table "os_inventory_invoices".
 *
 * @property int $id
 * @property int|null $inventory_items_id
 * @property int|null $company_id
 * @property int|null $number
 * @property float|null $single_price
 * @property int|null $type
 * @property int|null $suppliers_id
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $created_by
 * @property int|null $last_updated_by
 * @property int|null $is_deleted
 * @property string|null $date
 */
class InventoryInvoices extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'os_inventory_invoices';
    }
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'last_updated_by',
            ],
            [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('UNIX_TIMESTAMP()'),
            ],
            'softDeleteBehavior' => [
                'class' => SoftDeleteBehavior::className(),
                'softDeleteAttributeValues' => [
                    'is_deleted' => true
                ],

                'replaceRegularDelete' => true // mutate native `delete()` method
            ],

        ];
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['inventory_items_id', 'company_id', 'type', 'suppliers_id', 'created_at', 'updated_at', 'created_by', 'last_updated_by', 'is_deleted'], 'integer'],
            [['date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'inventory_items_id' => 'Inventory Items ID',
            'company_id' => 'Company ID',
            'type' => 'Type',
            'suppliers_id' => 'Suppliers ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'last_updated_by' => 'Last Updated By',
            'is_deleted' => 'Is Deleted',
            'date' => 'Date',
        ];
    }
    function beforeSave($insert)
    {
        $this->date = date('Y-m-d');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function getCreatedBy() {
        return $this->hasOne(\common\models\User::className(), ['id' => 'created_by']);
    }
    public function getUpdatedBy() {
        return $this->hasOne(\common\models\User::className(), ['id' => 'last_updated_by']);
    }
    public function getCompany() {
        return $this->hasOne(\backend\modules\companies\models\Companies::className(), ['id' => 'company_id']);
    }
    public function getInventoryItems() {
        return $this->hasOne(\backend\modules\inventoryItems\models\InventoryItems::className(), ['id' => 'inventory_items_id']);
    }
    public function getSuppliers() {
        return $this->hasOne(\backend\modules\inventorySuppliers\models\InventorySuppliers::className(), ['id' => 'suppliers_id']);
    }
    public static function find()
    {
        $query = parent::find();
        $query->attachBehavior('softDelete', SoftDeleteQueryBehavior::className());
        return $query->notDeleted();
    }
}
